#!/usr/bin/env php

<?php

use Oktaax\Console;
use Swoole\ExitException;

require_once __DIR__ . "/app/Command/Command.php";

require_once __DIR__ . "/vendor/autoload.php";

$argument = $argv;


$command = new Command();
if (count($argument) > 1) {

    try {
        $command->handle($argument);
    } catch (ExitException $e) {
        Console::info("Exit!");
    } catch (\Throwable $th) {
        Console::error($th->getMessage());
    }
} else {
    $commands = $command->getCommands();
    echo "available commands \n";
    echo "\n";
    foreach ($commands as $key => $value) {
        echo "$key : $value \n";
    }
    echo "\n";


    while ($f = readline()) {
        if ($f === "exit" || $f === "exit;") {
            echo "bye! ";
            sleep(1);
            exit;
        }
    }
}
