#!/usr/bin/env php

<?php

use Oktaax\Console;
use Swoole\ExitException;

require_once __DIR__ . "/app/Command/Command.php";

require_once __DIR__ . "/vendor/autoload.php";

$argument = $argv;


if (count($argument) > 1) {

    $command = new Command();
    try {
        $command->handle($argument);
    } catch (ExitException $e) {
        Console::info("Swoole Exit!");
    } catch (\Throwable $th) {
        Console::error($th->getMessage());
    }
} else {
    echo "empty arguments!\n";
}
