#!/bin/bash

echo "Cleaning up Docker containers, images, volumes, and networks..."

echo "Stopping all running containers..."
docker stop $(docker ps -q)

echo "Removing all containers..."
docker rm $(docker ps -aq)

echo "Removing all images..."
docker rmi $(docker images -q) --force

echo "Removing all volumes..."
docker volume rm $(docker volume ls -q) --force

echo "Removing all unused networks..."
docker network prune -f

echo "Cleaning up dangling resources..."
docker system prune -af --volumes

echo "Docker cleanup complete!"
